"use client";

import { useMemo, useState } from "react";
import type { FormEvent } from "react";
import { TireFlowIcon } from "@/components/tireflow-icons";
import { currency, demoProducts, type DemoProduct } from "@/lib/tireflow-demo-data";

export default function ProductsPage() {
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("Todos"); const [modal,setModal]=useState(false); const [products,setProducts]=useState(demoProducts);
  const visible=useMemo(()=>products.filter(p=>(category==="Todos"||p.category===category)&&`${p.code} ${p.name} ${p.brand} ${p.measure} ${p.dot}`.toLowerCase().includes(query.toLowerCase())),[products,query,category]);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const next:DemoProduct={id:`p${Date.now()}`,code:String(form.get("code")),name:String(form.get("name")),brand:String(form.get("brand")),category:String(form.get("category")),measure:String(form.get("measure")),condition:"Novo",stock:Number(form.get("stock")),minimum:Number(form.get("minimum")),cost:Number(form.get("cost")),price:Number(form.get("price")),location:String(form.get("location")),dot:String(form.get("dot")),active:true};setProducts([next,...products]);setModal(false)};
  return <>
    <header className="tireflow-page-head"><div><p className="tireflow-eyebrow">CATÁLOGO E RASTREABILIDADE</p><h1 className="tireflow-title">Produtos e Pneus</h1><p className="tireflow-subtitle">{products.length} itens cadastrados nesta demonstração.</p></div><div className="tireflow-actions"><button className="tireflow-btn"><TireFlowIcon name="download"/> Exportar</button><button className="tireflow-btn primary" onClick={()=>setModal(true)}><TireFlowIcon name="plus"/> Novo produto</button></div></header>
    <section className="tireflow-card tireflow-table-card"><div className="tireflow-toolbar"><label className="tireflow-filter"><TireFlowIcon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código, medida, marca, DOT ou série..."/></label><select className="tireflow-select" value={category} onChange={e=>setCategory(e.target.value)}><option>Todos</option>{[...new Set(products.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select></div><div className="tireflow-table-wrap"><table className="tireflow-table"><thead><tr><th>PRODUTO</th><th>MEDIDA</th><th>CONDIÇÃO / DOT</th><th>LOCAL</th><th>ESTOQUE</th><th>CUSTO</th><th>VENDA</th><th>STATUS</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.code} • {p.brand}</small></td><td><strong>{p.measure}</strong><small>{p.category}</small></td><td>{p.condition}<small>DOT {p.dot}</small></td><td>{p.location}</td><td><div className={`tireflow-stock ${p.stock<=p.minimum?"low":""}`}><b>{p.stock}</b><div className="tireflow-stock-bar"><span style={{width:`${Math.min(100,p.stock/Math.max(p.minimum,1)*50)}%`}}/></div></div><small>Mín. {p.minimum}</small></td><td>{currency(p.cost)}</td><td><strong>{currency(p.price)}</strong></td><td><span className="tireflow-badge">{p.active?"Ativo":"Inativo"}</span></td></tr>)}</tbody></table></div></section>
    {modal&&<div className="tireflow-modal"><form className="tireflow-form" onSubmit={submit}><div className="tireflow-form-head"><div><p className="tireflow-eyebrow">NOVO CADASTRO</p><h2>Produto ou pneu</h2></div><button type="button" onClick={()=>setModal(false)}>✕</button></div><div className="tireflow-form-body">{[["code","Código interno","PNE-0060"],["name","Nome do produto","Pneu Touring 88"],["brand","Marca","Marca Demo"],["measure","Medida","185/60 R15"],["category","Categoria","Pneu passeio"],["dot","DOT","2626"],["location","Localização","A-03-02"],["stock","Estoque inicial","8"],["minimum","Estoque mínimo","4"],["cost","Custo","350"],["price","Preço de venda","529.90"]].map(([name,label,placeholder])=><div className="tireflow-field" key={name}><label>{label.toUpperCase()}</label><input name={name} placeholder={placeholder} type={["stock","minimum","cost","price"].includes(name)?"number":"text"} step="0.01" required/></div>)}</div><div className="tireflow-form-actions"><button className="tireflow-btn" type="button" onClick={()=>setModal(false)}>Cancelar</button><button className="tireflow-btn primary">Cadastrar produto</button></div></form></div>}
  </>;
}
