import Link from "next/link";
import { TireFlowIcon } from "@/components/tireflow-icons";
import { currency, demoProducts } from "@/lib/tireflow-demo-data";

export default function StockPage(){
  const total=demoProducts.reduce((sum,p)=>sum+p.stock,0),value=demoProducts.reduce((sum,p)=>sum+p.stock*p.cost,0),low=demoProducts.filter(p=>p.stock<=p.minimum);
  return <><header className="tireflow-page-head"><div><p className="tireflow-eyebrow">POSIÇÃO ATUAL</p><h1 className="tireflow-title">Controle de Estoque</h1><p className="tireflow-subtitle">Visão consolidada por produto e localização física.</p></div><div className="tireflow-actions"><Link className="tireflow-btn" href="/movimentacoes?tipo=entrada"><TireFlowIcon name="plus"/> Registrar entrada</Link><Link className="tireflow-btn primary" href="/movimentacoes?tipo=saida"><TireFlowIcon name="move"/> Registrar saída</Link></div></header>
  <section className="tireflow-grid tireflow-kpis"><article className="tireflow-card tireflow-kpi"><div className="tireflow-kpi-icon blue"><TireFlowIcon name="stock"/></div><strong>{total}</strong><p>Unidades em estoque</p></article><article className="tireflow-card tireflow-kpi"><div className="tireflow-kpi-icon green"><TireFlowIcon name="trend"/></div><strong>{currency(value)}</strong><p>Capital em estoque (custo)</p></article><article className="tireflow-card tireflow-kpi"><div className="tireflow-kpi-icon red"><TireFlowIcon name="bell"/></div><strong>{low.length}</strong><p>Produtos abaixo do mínimo</p></article><article className="tireflow-card tireflow-kpi"><div className="tireflow-kpi-icon"><TireFlowIcon name="move"/></div><strong>36</strong><p>Entradas no mês • 29 saídas</p></article></section>
  <section className="tireflow-grid tireflow-two-cols" style={{marginTop:14}}><article className="tireflow-card"><div className="tireflow-panel-head"><h2>Estoque por localização</h2><span className="tireflow-badge">Atualizado agora</span></div><div className="tireflow-stat-list">{[["Setor A • Pneus passeio","16 unidades"],["Setor B • SUV e performance","9 unidades"],["Setor C • Utilitários","9 unidades"],["Setor D • Acessórios","38 unidades"]].map(r=><div className="tireflow-stat-row" key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong></div>)}</div></article><article className="tireflow-card"><div className="tireflow-panel-head"><h2>Reposição necessária</h2><Link href="/produtos">Ver produtos</Link></div><div className="tireflow-stat-list">{low.map(p=><div className="tireflow-stat-row" key={p.id}><span><strong>{p.measure}</strong> • {p.brand}</span><span className="tireflow-badge red">{p.stock} / mín. {p.minimum}</span></div>)}</div></article></section>
  <div className="tireflow-note" style={{marginTop:14}}><strong>Regra de integridade:</strong> movimentações concluídas não podem ser excluídas. Qualquer correção deve gerar um estorno vinculado ao registro original, preservando usuário, horário e justificativa.</div></>;
}
