import { ProductType,ServiceOrderStatus,StockMovementType } from "../src/generated/prisma/client";
import { prisma,pool } from "../src/lib/db/prisma";
async function main(){
 const org=await prisma.organization.findFirstOrThrow({where:{slug:"sena-borracharias"},include:{stores:true,memberships:{where:{role:"OWNER",status:"ACTIVE"}}}});
 const store=org.stores[0],membership=org.memberships[0]; if(!store||!membership)throw new Error("Pilot context unavailable.");
 await prisma.organization.update({where:{id:org.id},data:{legalName:"TireFlow Demonstração",tradeName:"TireFlow Demonstração"}});
 await prisma.store.update({where:{id:store.id},data:{name:"Unidade Matriz",code:"MATRIZ"}});
 const defs=[["PNEU-175","Pneu 175/70 R14",ProductType.TIRE,"Pneus","RoadMax","175/70 R14",14,260,390,4,12],["PNEU-185","Pneu 185/65 R15",ProductType.TIRE,"Pneus","DrivePro","185/65 R15",15,320,480,4,3],["PNEU-205","Pneu 205/55 R16",ProductType.TIRE,"Pneus","RoadMax","205/55 R16",16,410,610,4,0],["VALVULA","Válvula para pneu",ProductType.PRODUCT,"Acessórios","TireFlow",null,null,4,12,10,30],["REPARO","Kit de reparo",ProductType.PRODUCT,"Reparo","TireFlow",null,null,18,40,5,8],["SERV-ALI","Serviço de alinhamento",ProductType.SERVICE,"Serviços","TireFlow",null,null,0,90,0,0],["SERV-BAL","Serviço de balanceamento",ProductType.SERVICE,"Serviços","TireFlow",null,null,0,60,0,0]] as const;
 for(const [code,name,type,category,brand,size,rim,buy,sale,min,qty] of defs){const p=await prisma.product.upsert({where:{organizationId_internalCode:{organizationId:org.id,internalCode:code}},update:{name,type,category,brand,size,rim,purchasePrice:buy,salePrice:sale,minimumStock:min,active:true},create:{organizationId:org.id,internalCode:code,name,type,category,brand,size,rim,purchasePrice:buy,salePrice:sale,minimumStock:min}});if(type!==ProductType.SERVICE){await prisma.stockBalance.upsert({where:{organizationId_storeId_productId:{organizationId:org.id,storeId:store.id,productId:p.id}},update:{quantity:qty},create:{organizationId:org.id,storeId:store.id,productId:p.id,quantity:qty}});const exists=await prisma.stockMovement.findFirst({where:{organizationId:org.id,storeId:store.id,productId:p.id,document:`DEMO-${code}`}});if(!exists&&qty>0)await prisma.stockMovement.create({data:{organizationId:org.id,storeId:store.id,productId:p.id,userId:membership.userId,type:StockMovementType.ENTRY,quantity:qty,previousBalance:0,resultingBalance:qty,unitCost:buy,document:`DEMO-${code}`,reason:"carga de demonstração"}})}}
 const customerDefs=[["Cliente Demonstração 1","11990000001","DEM1A23","Fiat Strada"],["Cliente Demonstração 2","11990000002","DEM2B34","Chevrolet Onix"],["Cliente Demonstração 3","11990000003","DEM3C45","Volkswagen Saveiro"]];
 const customers=[];for(const [name,phone,plate,vehicle] of customerDefs){let c=await prisma.customer.findFirst({where:{organizationId:org.id,licensePlate:plate}});c=c??await prisma.customer.create({data:{organizationId:org.id,name,phone,whatsapp:phone,licensePlate:plate,vehicleModel:vehicle}});customers.push(c)}
 const tire=await prisma.product.findUniqueOrThrow({where:{organizationId_internalCode:{organizationId:org.id,internalCode:"PNEU-175"}}});
 for(const [number,status] of [[9001,ServiceOrderStatus.OPEN],[9002,ServiceOrderStatus.IN_PROGRESS],[9003,ServiceOrderStatus.FINISHED]] as const){await prisma.serviceOrder.upsert({where:{organizationId_storeId_number:{organizationId:org.id,storeId:store.id,number}},update:{status},create:{organizationId:org.id,storeId:store.id,customerId:customers[number-9001].id,responsibleUserId:membership.userId,number,vehicleModel:customers[number-9001].vehicleModel,licensePlate:customers[number-9001].licensePlate,description:"Serviço de demonstração",status,laborAmount:80,productsAmount:390,totalAmount:470,finishedAt:status==="FINISHED"?new Date():null,inventoryPostedAt:status==="FINISHED"?new Date():null,items:{create:{organizationId:org.id,productId:tire.id,quantity:1,unitPrice:390,totalPrice:390}}}})}
 console.log("Demo seed ready: TireFlow Demonstração | Unidade Matriz");
}
main().finally(async()=>{await prisma.$disconnect();await pool.end()});
